AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Queue Processor Function
Resources:
  QueueProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: queueProcessor.handler
      Runtime: nodejs14.x
      CodeUri: ./src
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !Ref MyQueue
      Events:
        MyQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MyQueue.Arn

  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MyQueue

Outputs:
  QueueProcessorFunction:
    Description: "Queue Processor Lambda Function ARN"
    Value: !GetAtt QueueProcessorFunction.Arn