AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description:  Authorized API

Parameters:
  EnvironmentType:
    Description: The environment type
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Prod
    ConstraintDescription: Must specify either 'Dev' or 'Prod'. Default is 'Dev'.

Globals:
  Function:
    Tracing: Active
    Runtime: nodejs16.x
    Architectures:
      - arm64
    MemorySize: 512
    Timeout: 30
    Environment:
      Variables:
        ENVIRONMENT: !Ref EnvironmentType
  Api:
    TracingEnabled: True

Resources:
  Auth:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Auth
      Handler: src/handlers/authorize.handler
      Runtime: nodejs16.x
      Timeout: 15
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "Users-${EnvironmentType}"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        EntryPoints:
          - src/handlers/authorize.ts

  LambdaAuthInvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/service-role/"
      Policies:
        - PolicyName: AuthInvoke
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !GetAtt Auth.Arn

  ExampleApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref EnvironmentType
      Auth:
        Authorizers:
          Auth:
            FunctionInvokeRole: !GetAtt LambdaAuthInvokeRole.Arn
            FunctionArn: !GetAtt Auth.Arn
            IdentitySource: "$request.header.Authorization"
            FunctionPayloadType: TOKEN

  # auth
  Authorization:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/authenticate.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "Users-${EnvironmentType}"
      Events:
        RestAuthGet:
          Type: Api
          Properties:
            Path: "/login"
            Method: post
            RestApiId: !Ref ExampleApi
    Metadata:
      BuildMethod: esbuild
      BuildProperties:

  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "MyQueue-${EnvironmentType}"

  MyQueueDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "MyQueueDLQ-${EnvironmentType}"

  MyQueueProcessor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/queueProcessor.handler
      Runtime: nodejs16.x
      MemorySize: 512
      Timeout: 30
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !Ref MyQueue
        - SQSPollingPolicy:
            QueueName: !Ref MyQueue
      Events:
        MyQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MyQueue.Arn
            BatchSize: 10
            MaximumBatchingWindowInSeconds: 10

  MyQueueDLQPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: MyQueueDLQPolicy
      Roles:
        - !GetAtt MyQueueProcessorRole.Arn
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sqs:SendMessage
            Resource: !GetAtt MyQueueDLQ.Arn

  MyQueueProcessorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: MyQueueProcessorPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt MyQueue.Arn

  MyQueueDLQSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt MyQueueDLQ.Arn
      Protocol: sqs
      TopicArn: !Ref MyQueue

  NewSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "NewSQSQueue-${EnvironmentType}"

  NewSQSQueueDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "NewSQSQueueDLQ-${EnvironmentType}"

  NewQueueProcessor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/newQueueProcessor.handler
      Runtime: nodejs16.x
      MemorySize: 512
      Timeout: 30
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !Ref NewSQSQueue
        - SQSPollingPolicy:
            QueueName: !Ref NewSQSQueue
      Events:
        NewQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt NewSQSQueue.Arn
            BatchSize: 10
            MaximumBatchingWindowInSeconds: 10

  NewQueueDLQPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: NewQueueDLQPolicy
      Roles:
        - !GetAtt NewQueueProcessorRole.Arn
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sqs:SendMessage
            Resource: !GetAtt NewSQSQueueDLQ.Arn

  NewQueueProcessorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: NewQueueProcessorPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt NewSQSQueue.Arn

  NewQueueDLQSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt NewSQSQueueDLQ.Arn
      Protocol: sqs
      TopicArn: !Ref NewSQSQueue

  NewAdditionalSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "NewAdditionalSQSQueue-${EnvironmentType}"

  NewAdditionalSQSQueueDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "NewAdditionalSQSQueueDLQ-${EnvironmentType}"

  NewAdditionalQueueProcessor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/newAdditionalQueueProcessor.handler
      Runtime: nodejs16.x
      MemorySize: 512
      Timeout: 30
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !Ref NewAdditionalSQSQueue
        - SQSPollingPolicy:
            QueueName: !Ref NewAdditionalSQSQueue
      Events:
        NewAdditionalQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt NewAdditionalSQSQueue.Arn
            BatchSize: 10
            MaximumBatchingWindowInSeconds: 10

  NewAdditionalQueueDLQPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: NewAdditionalQueueDLQPolicy
      Roles:
        - !GetAtt NewAdditionalQueueProcessorRole.Arn
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sqs:SendMessage
            Resource: !GetAtt NewAdditionalSQSQueueDLQ.Arn

  NewAdditionalQueueProcessorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: NewAdditionalQueueProcessorPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt NewAdditionalSQSQueue.Arn

  NewAdditionalQueueDLQSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt NewAdditionalSQSQueueDLQ.Arn
      Protocol: sqs
      TopicArn: !Ref NewAdditionalSQSQueue

  # New SQS and DLQ resources
  AdditionalSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "AdditionalSQSQueue-${EnvironmentType}"

  AdditionalSQSQueueDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "AdditionalSQSQueueDLQ-${EnvironmentType}"

  AdditionalQueueProcessor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/additionalQueueProcessor.handler
      Runtime: nodejs16.x
      MemorySize: 512
      Timeout: 30
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !Ref AdditionalSQSQueue
        - SQSPollingPolicy:
            QueueName: !Ref AdditionalSQSQueue
      Events:
        AdditionalQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt AdditionalSQSQueue.Arn
            BatchSize: 10
            MaximumBatchingWindowInSeconds: 10

  AdditionalQueueDLQPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AdditionalQueueDLQPolicy
      Roles:
        - !GetAtt AdditionalQueueProcessorRole.Arn
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sqs:SendMessage
            Resource: !GetAtt AdditionalSQSQueueDLQ.Arn

  AdditionalQueueProcessorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AdditionalQueueProcessorPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt AdditionalSQSQueue.Arn

  AdditionalQueueDLQSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt AdditionalSQSQueueDLQ.Arn
      Protocol: sqs
      TopicArn: !Ref AdditionalSQSQueue

Outputs:
  AuthFunction:
    Description: "Auth Lambda Function ARN"
    Value: !GetAtt Auth.Arn

  ExampleApiUrl:
    Description: "API Gateway endpoint URL for Prod stage for Auth function"
    Value: !Sub "https://${ExampleApi}.execute-api.${AWS::Region}.amazonaws.com/${EnvironmentType}/login"