name: Run Unit Tests & Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # validate:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: aws-actions/setup-sam@v2

  #     - name: sam fix https://github.com/aws/aws-sam-cli/issues/4527
  #       run: $(dirname $(readlink $(which sam)))/pip install --force-reinstall "cryptography==38.0.4"
  #     - uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
  #         aws-region: eu-west-2
  #     - name: Validate SAM Template
  #       run: sam validate

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2

      - name: Install Swagger CLI
        run: npm install -g @apidevtools/swagger-cli

      - name: Validate Swagger API Definitions
        run: swagger-cli validate swagger/etcauthapp-api-docs.yaml

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Block Aerial API Access
        run: |
          set -o xtrace
          sudo echo "0.0.0.0 api.eu.production.aerial-tech.net" | sudo tee -a /etc/hosts
          sudo cat /etc/hosts
          nslookup api.eu.production.aerial-tech.net

      - run: npm clean-install
      - run: npm run build --if-present
      - run: npm run test